import { UserRole } from 'libs/dto/auth';
import { PERMISSIONS } from './permissions.constant';

/**
 * Permissions par défaut pour chaque rôle
 */
export const DEFAULT_ROLE_PERMISSIONS: Record<UserRole, string[]> = {
  /**
   * ADMIN: Accès complet à toutes les fonctionnalités
   */
  [UserRole.ADMIN]: [
    // Déclarations - Full Access
    PERMISSIONS.DECLARATIONS_READ,
    PERMISSIONS.DECLARATIONS_CREATE,
    PERMISSIONS.DECLARATIONS_UPDATE,
    PERMISSIONS.DECLARATIONS_DELETE,
    PERMISSIONS.DECLARATIONS_APPROVE,
    PERMISSIONS.DECLARATIONS_REJECT,
    PERMISSIONS.DECLARATIONS_EXPORT,

    // Ordres de Mission - Full Access
    PERMISSIONS.ORDRE_MISSIONS_READ,
    PERMISSIONS.ORDRE_MISSIONS_CREATE,
    PERMISSIONS.ORDRE_MISSIONS_UPDATE,
    PERMISSIONS.ORDRE_MISSIONS_DELETE,
    PERMISSIONS.ORDRE_MISSIONS_ASSIGN,
    PERMISSIONS.ORDRE_MISSIONS_APPROVE,
    PERMISSIONS.ORDRE_MISSIONS_EXPORT,

    // Utilisateurs - Full Access
    PERMISSIONS.USERS_READ,
    PERMISSIONS.USERS_CREATE,
    PERMISSIONS.USERS_UPDATE,
    PERMISSIONS.USERS_DELETE,
    PERMISSIONS.USERS_ACTIVATE,
    PERMISSIONS.USERS_DEACTIVATE,
    PERMISSIONS.USERS_RESET_PASSWORD,
    PERMISSIONS.USERS_MANAGE_PERMISSIONS,

    // Agents - Full Access
    PERMISSIONS.AGENTS_READ,
    PERMISSIONS.AGENTS_CREATE,
    PERMISSIONS.AGENTS_UPDATE,
    PERMISSIONS.AGENTS_DELETE,
    PERMISSIONS.AGENTS_ASSIGN,

    // Maisons de Transit - Full Access
    PERMISSIONS.MAISONS_TRANSIT_READ,
    PERMISSIONS.MAISONS_TRANSIT_CREATE,
    PERMISSIONS.MAISONS_TRANSIT_UPDATE,
    PERMISSIONS.MAISONS_TRANSIT_DELETE,
    PERMISSIONS.MAISONS_TRANSIT_MANAGE_STAFF,

    // Maisons de Transit Requests - Full Access
    PERMISSIONS.MAISON_TRANSIT_REQUESTS_READ,
    PERMISSIONS.MAISON_TRANSIT_REQUESTS_INVITE,
    PERMISSIONS.MAISON_TRANSIT_REQUESTS_REVIEW,
    PERMISSIONS.MAISON_TRANSIT_REQUESTS_DELETE,

    // Bureaux de Sortie - Full Access
    PERMISSIONS.BUREAUX_SORTIES_READ,
    PERMISSIONS.BUREAUX_SORTIES_CREATE,
    PERMISSIONS.BUREAUX_SORTIES_UPDATE,
    PERMISSIONS.BUREAUX_SORTIES_DELETE,

    // Escouades - Full Access
    PERMISSIONS.ESCOUADES_READ,
    PERMISSIONS.ESCOUADES_CREATE,
    PERMISSIONS.ESCOUADES_UPDATE,
    PERMISSIONS.ESCOUADES_DELETE,
    PERMISSIONS.ESCOUADES_ASSIGN_AGENTS,

    // Dépositaires - Full Access
    PERMISSIONS.DEPOSITAIRES_READ,
    PERMISSIONS.DEPOSITAIRES_CREATE,
    PERMISSIONS.DEPOSITAIRES_UPDATE,
    PERMISSIONS.DEPOSITAIRES_DELETE,

    // Colis - Full Access
    PERMISSIONS.COLIS_READ,
    PERMISSIONS.COLIS_CREATE,
    PERMISSIONS.COLIS_UPDATE,
    PERMISSIONS.COLIS_DELETE,

    // Transports - Full Access
    PERMISSIONS.TRANSPORTS_READ,
    PERMISSIONS.TRANSPORTS_CREATE,
    PERMISSIONS.TRANSPORTS_UPDATE,
    PERMISSIONS.TRANSPORTS_DELETE,

    // Audit Logs - Full Access
    PERMISSIONS.AUDIT_LOGS_READ,
    PERMISSIONS.AUDIT_LOGS_EXPORT,

    // Permissions Management - Full Access
    PERMISSIONS.PERMISSIONS_READ,
    PERMISSIONS.PERMISSIONS_ASSIGN,
    PERMISSIONS.PERMISSIONS_REVOKE,

    // Régimes - Full Access
    PERMISSIONS.REGIMES_READ,
    PERMISSIONS.REGIMES_CREATE,
    PERMISSIONS.REGIMES_UPDATE,
    PERMISSIONS.REGIMES_DELETE,
  ],

  /**
   * SUPERVISEUR: Gestion complète des déclarations, ordres de mission, et consultation
   */
  [UserRole.SUPERVISEUR]: [
    // Déclarations - Full Access
    PERMISSIONS.DECLARATIONS_READ,
    PERMISSIONS.DECLARATIONS_CREATE,
    PERMISSIONS.DECLARATIONS_UPDATE,
    PERMISSIONS.DECLARATIONS_DELETE,
    PERMISSIONS.DECLARATIONS_APPROVE,
    PERMISSIONS.DECLARATIONS_REJECT,
    PERMISSIONS.DECLARATIONS_EXPORT,

    // Ordres de Mission - Full Access
    PERMISSIONS.ORDRE_MISSIONS_READ,
    PERMISSIONS.ORDRE_MISSIONS_CREATE,
    PERMISSIONS.ORDRE_MISSIONS_UPDATE,
    PERMISSIONS.ORDRE_MISSIONS_DELETE,
    PERMISSIONS.ORDRE_MISSIONS_ASSIGN,
    PERMISSIONS.ORDRE_MISSIONS_APPROVE,
    PERMISSIONS.ORDRE_MISSIONS_EXPORT,

    // Agents - Read and Assign
    PERMISSIONS.AGENTS_READ,
    PERMISSIONS.AGENTS_ASSIGN,

    // Bureaux de Sortie - Read Only
    PERMISSIONS.BUREAUX_SORTIES_READ,

    // Escouades - Full Access
    PERMISSIONS.ESCOUADES_READ,
    PERMISSIONS.ESCOUADES_CREATE,
    PERMISSIONS.ESCOUADES_UPDATE,
    PERMISSIONS.ESCOUADES_DELETE,
    PERMISSIONS.ESCOUADES_ASSIGN_AGENTS,

    // Dépositaires - Read Only
    PERMISSIONS.DEPOSITAIRES_READ,

    // Colis - Full Access
    PERMISSIONS.COLIS_READ,
    PERMISSIONS.COLIS_CREATE,
    PERMISSIONS.COLIS_UPDATE,
    PERMISSIONS.COLIS_DELETE,

    // Transports - Full Access
    PERMISSIONS.TRANSPORTS_READ,
    PERMISSIONS.TRANSPORTS_CREATE,
    PERMISSIONS.TRANSPORTS_UPDATE,
    PERMISSIONS.TRANSPORTS_DELETE,

    // Audit Logs - Read Only
    PERMISSIONS.AUDIT_LOGS_READ,

    // Maisons de Transit - Read Only
    PERMISSIONS.MAISONS_TRANSIT_READ,

    // Régimes - Read Only
    PERMISSIONS.REGIMES_READ,
  ],

  /**
   * AGENT: Création et modification des déclarations et ordres de mission
   */
  [UserRole.AGENT]: [
    // Déclarations - Create, Read, Update
    PERMISSIONS.DECLARATIONS_READ,
    PERMISSIONS.DECLARATIONS_CREATE,
    PERMISSIONS.DECLARATIONS_UPDATE,

    // Ordres de Mission - Create, Read, Update
    PERMISSIONS.ORDRE_MISSIONS_READ,
    PERMISSIONS.ORDRE_MISSIONS_CREATE,
    PERMISSIONS.ORDRE_MISSIONS_UPDATE,

    // Agents - Read Only
    PERMISSIONS.AGENTS_READ,

    // Bureaux de Sortie - Read Only
    PERMISSIONS.BUREAUX_SORTIES_READ,

    // Escouades - Read Only
    PERMISSIONS.ESCOUADES_READ,

    // Dépositaires - Read Only
    PERMISSIONS.DEPOSITAIRES_READ,

    // Colis - Create, Read, Update
    PERMISSIONS.COLIS_READ,
    PERMISSIONS.COLIS_CREATE,
    PERMISSIONS.COLIS_UPDATE,

    // Transports - Create, Read, Update
    PERMISSIONS.TRANSPORTS_READ,
    PERMISSIONS.TRANSPORTS_CREATE,
    PERMISSIONS.TRANSPORTS_UPDATE,

    // Maisons de Transit - Read Only
    PERMISSIONS.MAISONS_TRANSIT_READ,

    // Maisons de Transit Requests - Invite and Read
    PERMISSIONS.MAISON_TRANSIT_REQUESTS_READ,
    PERMISSIONS.MAISON_TRANSIT_REQUESTS_INVITE,

    // Régimes - Read Only
    PERMISSIONS.REGIMES_READ,
  ],

  /**
   * TRANSITAIRE: Consultation limitée à ses propres ressources
   */
  [UserRole.TRANSITAIRE]: [
    // Déclarations - Read Only (seulement ses déclarations)
    PERMISSIONS.DECLARATIONS_READ,

    // Ordres de Mission - Read and Create (seulement les siens)
    PERMISSIONS.ORDRE_MISSIONS_READ,
    PERMISSIONS.ORDRE_MISSIONS_CREATE,

    // Maisons de Transit - Read Only (seulement la sienne)
    PERMISSIONS.MAISONS_TRANSIT_READ,

    // Dépositaires - Read Only
    PERMISSIONS.DEPOSITAIRES_READ,

    // Colis - Read and Create
    PERMISSIONS.COLIS_READ,
    PERMISSIONS.COLIS_CREATE,

    // Transports - Read and Create
    PERMISSIONS.TRANSPORTS_READ,
    PERMISSIONS.TRANSPORTS_CREATE,

    // Bureaux de Sortie - Read Only
    PERMISSIONS.BUREAUX_SORTIES_READ,

    // Régimes - Read Only
    PERMISSIONS.REGIMES_READ,
  ],

  /**
   * DECLARANT: Création et gestion des déclarations pour sa maison de transit
   */
  [UserRole.DECLARANT]: [
    // Déclarations - Full CRUD (seulement pour sa maison de transit)
    PERMISSIONS.DECLARATIONS_READ,
    PERMISSIONS.DECLARATIONS_CREATE,
    PERMISSIONS.DECLARATIONS_UPDATE,
    PERMISSIONS.DECLARATIONS_DELETE,

    // Ordres de Mission - Read and Create
    PERMISSIONS.ORDRE_MISSIONS_READ,
    PERMISSIONS.ORDRE_MISSIONS_CREATE,
    PERMISSIONS.ORDRE_MISSIONS_UPDATE,

    // Maisons de Transit - Read Only (seulement la sienne)
    PERMISSIONS.MAISONS_TRANSIT_READ,

    // Dépositaires - Read and Create
    PERMISSIONS.DEPOSITAIRES_READ,
    PERMISSIONS.DEPOSITAIRES_CREATE,

    // Colis - Full CRUD
    PERMISSIONS.COLIS_READ,
    PERMISSIONS.COLIS_CREATE,
    PERMISSIONS.COLIS_UPDATE,
    PERMISSIONS.COLIS_DELETE,

    // Transports - Full CRUD
    PERMISSIONS.TRANSPORTS_READ,
    PERMISSIONS.TRANSPORTS_CREATE,
    PERMISSIONS.TRANSPORTS_UPDATE,
    PERMISSIONS.TRANSPORTS_DELETE,

    // Bureaux de Sortie - Read Only
    PERMISSIONS.BUREAUX_SORTIES_READ,

    // Régimes - Read Only
    PERMISSIONS.REGIMES_READ,
  ],
};

/**
 * Vérifier si un rôle a une permission par défaut
 */
export function roleHasPermission(role: UserRole, permission: string): boolean {
  return DEFAULT_ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

/**
 * Obtenir toutes les permissions d'un rôle
 */
export function getRolePermissions(role: UserRole): string[] {
  return DEFAULT_ROLE_PERMISSIONS[role] ?? [];
}
